---
title: Nagasurya Tirunagaru
logo: "/images/logo.jpg?raw=true" #
description: > #text below
  I am a student pursuing their masters degree in business analytics from university of texas at dallas. 
  I believe numbers tell us a tale, and it is my job to understand it.
  Perfection is not something that theoretically achieved in a practical world where unforeseen factors impact the result, but i believe strivng towards unattainable limits is what make us successful.
  <br><br>
  <a href="https://www.linkedin.com/in/suryatirunagaru/">View My LinkedIn Profile</a> 
show_downloads: false
theme: jekyll-theme-minimal
...
